"""Create food_nutritions table

Revision ID: ceceac37d0f1
Revises: 
Create Date: 2025-05-22 04:12:28.681856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceceac37d0f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_nutritions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_cd', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('research_year', sa.String(length=4), nullable=True),
    sa.Column('maker_name', sa.String(length=100), nullable=True),
    sa.Column('ref_name', sa.String(length=255), nullable=True),
    sa.Column('serving_size', sa.Float(), nullable=True),
    sa.Column('calorie', sa.Float(), nullable=True),
    sa.Column('carbohydrate', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('province', sa.Float(), nullable=True),
    sa.Column('sugars', sa.Float(), nullable=True),
    sa.Column('salt', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Float(), nullable=True),
    sa.Column('saturated_fatty_acids', sa.Float(), nullable=True),
    sa.Column('trans_fat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_nutritions_food_cd'), 'food_nutritions', ['food_cd'], unique=True)
    op.create_index(op.f('ix_food_nutritions_food_name'), 'food_nutritions', ['food_name'], unique=False)
    op.create_index(op.f('ix_food_nutritions_id'), 'food_nutritions', ['id'], unique=False)
    op.create_index(op.f('ix_food_nutritions_maker_name'), 'food_nutritions', ['maker_name'], unique=False)
    op.create_index(op.f('ix_food_nutritions_research_year'), 'food_nutritions', ['research_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_nutritions_research_year'), table_name='food_nutritions')
    op.drop_index(op.f('ix_food_nutritions_maker_name'), table_name='food_nutritions')
    op.drop_index(op.f('ix_food_nutritions_id'), table_name='food_nutritions')
    op.drop_index(op.f('ix_food_nutritions_food_name'), table_name='food_nutritions')
    op.drop_index(op.f('ix_food_nutritions_food_cd'), table_name='food_nutritions')
    op.drop_table('food_nutritions')
    # ### end Alembic commands ###
